apiVersion: v1
kind: pod
metadata:
  name: empty-dir-demo
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /etc/config
      name: nginx-logs
      
  - name: almalinux
    image: almalinux:9
  volumes:
  - name: nginx-logs
    emptyDir:
      sizeLimit: 100Mi