apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  # these are replica set labels
  labels:
    purpose: rs-demo
    project: roboshop
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
  # these labels are used to select pods
    matchLabels:
      purpose: rs-demo
      project: roboshop
      # pod defination
  template:
    metadata:
      labels:
        purpose: rs-demo
        project: roboshop
    spec:
      containers:
      - name: nginx
        image: nginx